In [83]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cpu


### Introduction to Tensors

##### Creating tensors

In [84]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [85]:
scalar.ndim

0

In [86]:
scalar.item()

7

In [87]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [88]:
vector.ndim

1

In [89]:
vector.shape

torch.Size([2])

In [90]:
# MATRIX
MATRIX = torch.tensor([
    [1,2],
    [3,4]
])

In [91]:
MATRIX.ndim

2

In [92]:
MATRIX.shape

torch.Size([2, 2])

In [93]:
MATRIX[1]

tensor([3, 4])

In [94]:
# TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [19,20,21],
        [22,23,24],
        [25,26,27]
    ]
])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [95]:
TENSOR.ndim

3

In [96]:
TENSOR.shape

torch.Size([3, 3, 3])

In [97]:
TENSOR[0,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [98]:
TENSOR.view(3,9)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [99]:
# Random Tensors
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.8234, 0.4177, 0.7306, 0.2259],
        [0.3644, 0.8990, 0.0333, 0.8411],
        [0.0847, 0.7205, 0.4199, 0.6280]])

In [100]:
rand_tensor.shape

torch.Size([3, 4])

In [101]:
rand_tensor.ndim

2

In [102]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#### Zeros and ones

In [103]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [104]:
zeros * rand_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [105]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [106]:
ones.dtype

torch.float32

In [107]:
rand_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [108]:
# Use torch.range()
torch.range(1,11,2)

C:\Users\mehul\AppData\Local\Temp\ipykernel_25536\146279835.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,11,2)


tensor([ 1.,  3.,  5.,  7.,  9., 11.])

In [109]:
one_to_ten = torch.arange(start=1, end=11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [111]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [112]:
float_32_tensor.dtype

torch.float32

In [113]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [114]:
float_16_tensor.dtype

torch.float16

In [115]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [116]:
int_32_tensor = torch.tensor([3,6,9],
                            dtype=torch.int32,
                            device=None,
                            requires_grad=False)


In [117]:
int_32_tensor.dtype

torch.int32

In [118]:
(float_32_tensor * int_32_tensor).dtype

torch.float32

In [119]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7623, 0.3352, 0.7827, 0.4142],
        [0.1516, 0.3158, 0.6031, 0.1990],
        [0.4536, 0.3273, 0.3192, 0.2917]])

In [120]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Elements along 0 axis: {some_tensor.size(0)}")
print(f"Elements along 1 axis: {some_tensor.size(1)}")
print(f"Total number of elements in tensor: {some_tensor.numel()}")
print(f"Total number of elements in tensor: {some_tensor.nelement()}")


tensor([[0.7623, 0.3352, 0.7827, 0.4142],
        [0.1516, 0.3158, 0.6031, 0.1990],
        [0.4536, 0.3273, 0.3192, 0.2917]])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Shape of tensor: torch.Size([3, 4])
Elements along 0 axis: 3
Elements along 1 axis: 4
Total number of elements in tensor: 12
Total number of elements in tensor: 12


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division (element-wise)
* Matrix multiplication

In [121]:
# create a tensor and add to it
tensor = torch.Tensor([1,2,3])
tensor + 100

tensor([101., 102., 103.])

In [122]:
# Multiply tensor by 10
tensor * 10

tensor([10., 20., 30.])

In [123]:
# subtract 10
tensor - 10

tensor([-9., -8., -7.])

In [124]:
# trying pytorch in-built function
torch.mul(tensor, 10)

tensor([10., 20., 30.])

In [125]:
torch.add(tensor, 10)

tensor([11., 12., 13.])

### Matrix Multiplication

In [126]:
tensor * tensor

tensor([1., 4., 9.])

In [127]:
torch.matmul(tensor, tensor.T)

tensor(14.)

In [128]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [129]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14.)

In [130]:
%%time
torch.matmul(tensor, tensor.T)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14.)

In [131]:
%%time
np.matmul(tensor, tensor.T)

CPU times: total: 0 ns
Wall time: 1.21 ms


tensor(14.)

In [132]:
torch.matmul(torch.rand(1,6), torch.rand(6,6))

tensor([[1.8942, 1.5960, 1.2765, 1.8456, 1.3382, 1.3822]])

In [133]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([
    [1,2],
    [4,5],
    [7,8]
])
tensor_B = torch.tensor([
    [7,10],
    [8,11],
    [9,12]
])
print(tensor_A.shape, tensor_B.shape)
# torch.matmul(tensor_A, tensor_B)

torch.Size([3, 2]) torch.Size([3, 2])


In [134]:
# Use transpose to fix this
tensor_B.T.shape

torch.Size([2, 3])

In [135]:
tensor_B.shape

torch.Size([3, 2])

In [136]:
tensor_A, tensor_B.T

(tensor([[1, 2],
         [4, 5],
         [7, 8]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [137]:
# The matrix Multiplication FIX using transpose
print(f"Original shape: tensor_A {tensor_A.shape}, tensor_B =  {tensor_B.T.shape}")
print(f"New shape: tensor_A {tensor_A.shape}, tensor_B =  {tensor_B.T.shape}")
output_tensor = torch.matmul(tensor_A, tensor_B.T)
print(f"Output shape: {output_tensor.shape}")
output_tensor

Original shape: tensor_A torch.Size([3, 2]), tensor_B =  torch.Size([2, 3])
New shape: tensor_A torch.Size([3, 2]), tensor_B =  torch.Size([2, 3])
Output shape: torch.Size([3, 3])


tensor([[ 27,  30,  33],
        [ 78,  87,  96],
        [129, 144, 159]])

### Tensor aggregation mean max avg

In [138]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [139]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [140]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [141]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [142]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [143]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [144]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [145]:
x[0], x[9]

(tensor(0), tensor(90))

#### Reshaping, Staking, squeezing and unsqueezing

In [146]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [147]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [148]:
# Change the view of the tensor
z = x.view(1,9)
z, z.shape

# Changing z changees x (because a view is a way of looking at the same data in a different shape)

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [149]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [150]:
# Stack tensors on top of each other
x_stack = torch.stack((x,x,x,x,), dim=0)
x_stack, x_stack.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [151]:
# Squueze the tensor (remove all 1 dimensions) and unsqueeze it
x_reshaped_squeezed = x_reshaped.squeeze()
x_reshaped_squeezed, x_reshaped_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [152]:
x_reshaped_squeezed_unsqueezed = x_reshaped_squeezed.unsqueeze(dim=1)
x_reshaped_squeezed_unsqueezed, x_reshaped_squeezed_unsqueezed.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [153]:
# torch.permute is used to change the order of dimensions of a tensor
x_original = torch.rand((224,224,3))

# permute the dimensions
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

#### Indexing (selecting data from tensors)

In [154]:
# create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [155]:
x[0] #First bracket is the batch, second is the row, third is the column

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [156]:
x[0][0] , x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [157]:
x[0][0][0] , x[0, 0, 0]

(tensor(1), tensor(1))

In [158]:
x[0][1][1]

tensor(5)

In [159]:
x[0,2,2]

tensor(9)

In [160]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [161]:
x[0, 1, 1]

tensor(5)

In [162]:
x[0,0,:]

tensor([1, 2, 3])

In [163]:
x[0,-1,-1]

tensor(9)

In [164]:
x[0,:,2]

tensor([3, 6, 9])

#### PyTorch tensors & NumPy

In [169]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [170]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [171]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [190]:
tensor = tensor.add_(1)
tensor, numpy_tensor

(tensor([18., 18., 18., 18., 18., 18., 18.]),
 array([4., 4., 4., 4., 4., 4., 4.], dtype=float32))

#### reproducbility 

Using `Random seed` also generator

In [ ]:
torch.rand(3,3)

tensor([[0.8833, 0.9728, 0.4842],
        [0.3480, 0.1876, 0.7103],
        [0.6197, 0.2925, 0.1508]])

In [197]:
# create 2 tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A == random_tensor_B)
random_tensor_A, random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


(tensor([[0.0556, 0.6718, 0.3909, 0.0464],
         [0.1984, 0.3638, 0.4957, 0.6402],
         [0.2413, 0.5134, 0.5966, 0.4904]]),
 tensor([[0.7039, 0.5851, 0.3411, 0.1994],
         [0.4751, 0.8139, 0.0302, 0.3927],
         [0.2259, 0.6627, 0.7019, 0.4244]]))

In [202]:
# set the random seed
RANDOM_SEED = 42

gen = torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

gen = torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C == random_tensor_D)
random_tensor_C, random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

### Running tensors and PyTorch objects on the GPUs

In [206]:
torch.cuda.is_available()

False

In [207]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [208]:
# count number of gpu
torch.cuda.device_count()

0

### Putting tensor on GPU

In [209]:
# Create a tensor
tensor = torch.tensor([1,2,3], device=device)   
tensor.device

device(type='cpu')

In [212]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [217]:
tensor_on_gpu.detach().numpy()

array([1, 2, 3], dtype=int64)